# Generated by Django 3.2.11 on 2022-01-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
