# Generated by Django 4.0.1 on 2022-01-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_email_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='user',
            new_name='host',
        ),
    ]
