# Generated by Django 4.0.1 on 2022-01-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_rename_user_email_host'),
        ('hello', '0007_auto_20220121_1557'),
    ]

    operations = [
    ]
