# Generated by Django 4.0.1 on 2022-01-23 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0008_merge_20220123_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='host',
            new_name='user',
        ),
        migrations.AddField(
            model_name='email',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
